# Generated by Django 3.0.6 on 2020-05-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200511_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Class'),
        ),
    ]
