# Generated by Django 3.0.6 on 2020-05-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200516_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='user',
        ),
    ]
